### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by mxmilkb** [ryukau/VSTPlugins#1]
There is a [discussion](https://linuxmusicians.com/viewtopic.php?f=24&t=20517) on LinuxMusicians about the plugin. It has been noted that few Linux audio apps run VST3 plugins. LV2 is the primary plugin format of most Linux audio software. If there were an LV2 version of SevenDelay, it would allow more apps and users to run it. Possibly [DPF](https://github.com/DISTRHO/DPF) could help there.

Further information:
* http://lv2plug.in/
* https://github.com/drobilla/lv2/wiki

**Comment by ryukau** [comment]
Hi, mxmilkb.

I'll look into the porting to LV2 when I have time. Currently I have other priorities, so can't promise when to start.

Just in case, SevenDelay 0.1.0 had some bugs and it won't run on any DAW on Ubuntu. I've already fixed them and will update to 0.1.1 soon.

**Comment by ryukau** [comment]
SevenDelay and SyncSawSynth was ported to LV2.

See https://github.com/ryukau/LV2Plugins .
