### ISSUE TITLE
Build in Fedora 32

### ISSUE THREAD

**Issue by dacrhu** [ryukau/VSTPlugins#10]
Hi,

I can't build your plugins in Fedora 32.

> [ 17%] Built target vstgui
> Scanning dependencies of target vstgui_uidescription
> [ 17%] Building CXX object vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/editing/uieditcontroller.cpp.o
> [ 18%] Linking CXX static library ../../../lib/Release/libvstgui_uidescription.a
> [ 33%] Built target vstgui_uidescription
> [ 34%] Built target vstgui_support
> [ 37%] Built target vstgui_standalone
> [ 37%] Linking CXX executable ../../../../bin/Release/ImageStitcher/ImageStitcher
> [ 38%] Built target ImageStitcher
> [ 38%] Linking CXX executable ../../../../bin/Release/uidesccompressor
> [ 39%] Built target uidesccompressor
> [ 41%] Built target pluginterfaces
> [ 43%] Built target base
> [ 43%] Building CXX object public.sdk/CMakeFiles/sdk.dir/source/common/threadchecker_linux.cpp.o
> /home/berci/develop/vst/vst3sdk/public.sdk/source/common/threadchecker_linux.cpp: In member function ‘virtual bool Steinberg::Vst::LinuxThreadChecker::test(const char*, bool)’:
> /home/berci/develop/vst/vst3sdk/public.sdk/source/common/threadchecker_linux.cpp:56:13: error: ‘stderr’ was not declared in this scope
>    56 |    fprintf (stderr, "%s", failmessage);
>       |             ^~~~~~
> /home/berci/develop/vst/vst3sdk/public.sdk/source/common/threadchecker_linux.cpp:38:1: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
>    37 | #include "threadchecker.h"
>   +++ |+#include <cstdio>
>    38 | 
> /home/berci/develop/vst/vst3sdk/public.sdk/source/common/threadchecker_linux.cpp:56:4: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
>    56 |    fprintf (stderr, "%s", failmessage);
>       |    ^~~~~~~
>       |    wprintf
> gmake[2]: *** [public.sdk/CMakeFiles/sdk.dir/build.make:109: public.sdk/CMakeFiles/sdk.dir/source/common/threadchecker_linux.cpp.o] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:1091: public.sdk/CMakeFiles/sdk.dir/all] Error 2
> gmake: *** [Makefile:104: all] Error 2

I followed the construction instructions you described in everything.
Can you help me?

Thank you,
David

**Comment by ryukau** [comment]
Thanks for the report.

I made a fresh Fedora 32 VM and got same error. Changing `vst3sdk/public.sdk/source/common/threadchecker_linux.cpp` as following solved the error.

```c++
#if SMTG_OS_LINUX // Line 39

#include <cstdio> // Add this line.
#include <pthread.h>
```

Could you test this?

**Comment by dacrhu** [comment]
Working fine, thank you!

**Comment by ryukau** [comment]
Thanks for confirmation.

This is a issue in VST 3 SDK. So I'll keep open this issue until it will be fixed in upstream.

**Comment by ryukau** [comment]
VST 3 SDK 3.7.1 resolved this issue. If the problem still persists, feel free to add comment. I'll .
