### ISSUE TITLE
ClangCymbal is not loading in some DAWs

### ISSUE THREAD

**Issue by nekotaro6** [ryukau/VSTPlugins#19]
ClangCymbal is not loading in Ableton Live 11 and Bitwig Studio 4. This happens on both Windows and Mac M1. REAPER and FL Studio load ClangCymbal without problems on both platforms. Attached screenshots from Windows (Live and Bitwig).
![ClangCymbalWinLive](https://user-images.githubusercontent.com/107208256/184236064-9a6217b4-719d-41b2-9e24-231b0b1b2893.PNG)
![ClangCymbalWinBitwig](https://user-images.githubusercontent.com/107208256/184236142-509a7942-ef7d-40df-b07c-04085ee801ac.PNG)

**Comment by ryukau** [comment]
Thanks for the bug report.

I made a fix, and it's working on Bitwing and Live11 on Windows. Following is a download link to the fixed version. Let me know if it also works on macOS.

[ClangCymbal_beta4.zip](https://github.com/ryukau/VSTPlugins/files/9312569/ClangCymbal_beta4.zip)

**Comment by nekotaro6** [comment]
Fix is working on Mac on Bitwig and Live. Thank you.

**Comment by ryukau** [comment]
Thanks for testing. Fixed version is pushed, and it will available as next release.
