### ISSUE TITLE
Solution for VSTs not visible in DAW under MacOS

### ISSUE THREAD

**Issue by opasquetdotfr** [ryukau/VSTPlugins#27]
If you do not see @ryukau's wonderful plugins in your DAW under MacOS.

You should type in the Terminal:
sudo codesign --force --deep -s - /Library/Audio/Plug-Ins/VST3/xxx.vst3
OR
codesign --force --deep -s - ~/Library/Audio/Plug-Ins/VST3/xxx.vst3

In case of an error, try this command before:
sudo xattr -c /Library/Audio/Plug-Ins/VST3/xxx.vst3
OR
xattr -c ~/Library/Audio/Plug-Ins/VST3/xxx.vst3

**Comment by ryukau** [comment]
Thanks for the information.

I'll add `codesign` command to manual on next release.

**Comment by jazzman31** [comment]
> If you do not see @ryukau's wonderful plugins in your DAW under MacOS.
> 
> You should type in the Terminal: sudo codesign --force --deep -s - /Library/Audio/Plug-Ins/VST3/xxx.vst3 OR codesign --force --deep -s - ~/Library/Audio/Plug-Ins/VST3/xxx.vst3
> 
> In case of an error, try this command before: sudo xattr -c /Library/Audio/Plug-Ins/VST3/xxx.vst3 OR xattr -c ~/Library/Audio/Plug-Ins/VST3/xxx.vst3

It didn't work...

**Comment by ryukau** [comment]
Hi, @jazzman31.

Informations like:

- macOS version,
- what DAW you are using,
- what command you run,
- what error you got,

are lacking, so I can't comment on your specific case.

In general, `codesign` command is probably not required, unless you are going to use `full` zip package. `full` package is the one without `macOS` in file name. Also I'm not sure if `codesign` is available on macOS by default. Installation of Xcode might be required.

On `macOS` zip packages, `xattr` command is probably the only one that is required. Make sure to change the path to appropriate one. Following video might be useful if you aren't familiar with terminal. (Just in case, I'm not the author of the video.)

https://www.youtube.com/watch?v=0UOg0-wx8Jg

I also got an email which said that following app solved the issue on their macOS environment.

https://pelennor.gumroad.com/l/djesj

There's also a section in manual that trying to address installation issue on macOS.

https://ryukau.github.io/VSTPlugins/manual/ParallelDetune/ParallelDetune_en.html#macos-specific

Hope this helps.

**Comment by ryukau** [comment]
I added "[Applying `codesign`](https://ryukau.github.io/VSTPlugins/manual/ParallelDetune/ParallelDetune_en.html#applying-codesign)" section in manual.

I'll close this issue for now. If there are some problem or confirmation about installation on macOS, feel free to add comment here, or open another issue.
