### ISSUE TITLE
Trouble with Renoise

### ISSUE THREAD

**Issue by KlashKontakt** [ryukau/VSTPlugins#28]
Hello!
Renoise closes with an error when working with the plugin interface. When I try to twist the settings of any ester, during playback, the plugin kills the application and comes out with an error.

Incredible thanks for your work! Even errors and crashes do not let me abandon your plugins!

osx 12.3.1 m1 and intel
Renoise 3.4.2

Thnx for Your time!

**Comment by ryukau** [comment]
Hi, @KlashKontakt.

I probably got same error on my environemnt (Renoise 3.4.2 on Windows 10).

Steps to reproduce for instrument plugins:

1. Launch Renoise.
2. Open Plugin tab.
3. Load an instrument plugin on this repository.
4. Go to some other tab (Edit, Mix, Sampler, MIDI).
5. Go back to Plugin tab.
6. Edit parameter on plugin GUI.

Steps to reproduce for effect plugins:

1. Launch Renoise.
2. Open Mix tab.
3. Drag & drop an effect plugin on this repository to one of mixer channel.
4. Repeatedly open and close plugin GUI by clicking Ext. Editor several times.

I'll work on it, but it will take some time. Sorry for inconvenience.

**Comment by KlashKontakt** [comment]
Great news! can't wait new relies!

**Comment by ryukau** [comment]
I applied some fixes on aa58b94. At least plugins doesn't crash on my Windows environment.

@KlashKontakt Could you test plugins on following link? I'd like to know if they also work on Mac.

https://drive.google.com/file/d/1vPMxj8Mb24N5gZD2CtgK9ZEhPrgsqlpO/view?usp=sharing

**Comment by KlashKontakt** [comment]
Thanks a lot. Tested on the plugins that I use the most and so far there have been no failures. I'll check out the rest a bit later. 

incredible thanks!

**Comment by KlashKontakt** [comment]
I have been using quite a lot of your tools for several days now and everything works as it should.  Thank you.

**Comment by ryukau** [comment]
@KlashKontakt Thanks for testing!

The fix will be released as `UhhyouPlugins0.53.0`, after like 20 minute from this comment.

Beware that the zip file linked in this issue contained some alpha version plugins (See the list below). Breaking changes might be introduced to them. So I'd recommend not to use them, or render the result to audio file after using them.

- FoldShaper
- ModuloShaper
- OddPowShaper
- SoftClipper
- MatrixShifter

**Comment by KlashKontakt** [comment]
I have some suggestion for you.  I haven't seen more creative plugins for a long time.  Thanks again for this opportunity, which helps to diversify creativity and writing music in general.  could you make a plug-in with the possibility of fm mixing by means of a side chain?  that is, the idea is that in the mixing console to be able to mix 2 intersecting signals by means of FM modulation.  where one signal modulates another.  I have already tried something similar with ring modulation and it makes perfect sense.  but the real FM effect can be quite something new.  Thank you.

**Comment by ryukau** [comment]
@KlashKontakt I opened discussion about your suggestion. See following link.

[Frequency modulation of arbitrary 2 signal · ryukau/VSTPlugins · Discussion #29](https://github.com/ryukau/VSTPlugins/discussions/29)
