### ISSUE TITLE
Support vst3sdk 3.7.8

### ISSUE THREAD

**Issue by cbix** [ryukau/VSTPlugins#38]
vst3sdk 3.7.8 apparently includes some breaking changes when building plugins. I couldn't fully wrap my head around them but it seems we're now supposed to include the SDK in the plugin project (not the other way around as done previously) but not sure, it's not documented in [the changelog](https://forums.steinberg.net/t/vst-3-7-8-sdk-released/849397)...

How can I build the plugins with vst3sdk 3.7.8?

**Comment by ryukau** [comment]
Hi, @cbix.

If you are in hurry, the fix to VSTSDK 3.7.8 is already available on `develop` branch (42ecd11). If you can wait for a bit, then I can merge the patch to `master`. It will take 2-3 days to mostly update and verify manuals.

**Comment by ryukau** [comment]
Ah, I forgot to mention the main reason for pending. I'll probably merge all license texts to one file.

Also updated build instruction is available below. Ubuntu CI script might also be useful.

- [New build instruction](https://github.com/ryukau/VSTPlugins/blob/develop/build_instruction.md)
- [Ubuntu CI script](https://github.com/ryukau/VSTPlugins/blob/develop/ci/ci_ubuntu.sh)

**Comment by cbix** [comment]
Oh perfect, thanks for the quick response, I'll just use the fix from develop :) Closing since it's already fixed there.
