### ISSUE TITLE
Recent Update only builds CubicPadSynth

### ISSUE THREAD

**Issue by tank-trax** [ryukau/VSTPlugins#4]
Using Debian Buster 10.3

recent commit 8120ae8 only builds the CubicPadSynth (LV2, VST2 and standalone)

none of the other plugins were built

also this:
![Screenshot_20200305_111819](https://user-images.githubusercontent.com/41337033/76001440-157f5c00-5ed3-11ea-802e-f7ac87bca82b.png)

**Comment by ryukau** [comment]
Thanks for the report. I fixed build target on LV2Plugins repository.

GUI problem may be solved by patching DPF. Move to LV2Plugins directory and run `./patch.sh` or following command.

```bash
cp patch/NanoVG.cpp lib/DPF/dgl/src/NanoVG.cpp
```

**Comment by tank-trax** [comment]
applying the patch.sh appears to have corrected the GUI issue

![Screenshot_20200305_122905](https://user-images.githubusercontent.com/41337033/76008011-f08fe680-5edc-11ea-8428-6547051e73d1.png)

**Comment by ryukau** [comment]
It looks like working. If there's other issues, feel free to reopen this issue or make another issue.

**Comment by tank-trax** [comment]
it was in the LV2plugins (apologies) and yes it's all good now

thanks
