### ISSUE TITLE
Separate manuals to another repository

### ISSUE THREAD

**Issue by ryukau** [ryukau/VSTPlugins#42]
Sometimes I found typo, or failed to put proper links. In these cases, I'd like to update manuals without triggering CI that is setup on this repository, as it takes 20+ minutes to finish. I'm using GitHub for free, so I'd like to reduce the unnecessary usage.

However, I'm still not sure if this is a good idea or not. When using submodules, ref also must be updated on the main repository.

**Comment by fotisandstuff** [comment]
I don't know about manuals, but I'd suggest placing the plugin presets in a different repository. Github's "releases" menu isn't always reliable, as presets are sometimes forgotten under old releases.

**Comment by ryukau** [comment]
Hi, @fotisandstuff.

A while ago, I got a email from a user who suggested that it's better to include presets into zip archive. I kind of agree to that idea. The reason I separated presets are just from my inexperience. I thought it would take too much disk space, but it turns out that they are well under 100 KiB.

For now, you can download all the presets from [`presets/Uhhyou`](https://github.com/ryukau/VSTPlugins/tree/master/presets/Uhhyou) directory.

I opened a new issue (#44) for this topic.

---

On the original issue, I decided that it's better to move the manuals into another repo. The github pages in this repository will be replaced to a simple link redirects to new URL.

**Comment by fotisandstuff** [comment]
Thank you!

**Comment by ryukau** [comment]
Manuals are separated to the link below.

- [ryukau/UhhyouManuals: Documentation of Uhhyou Plugins.](https://github.com/ryukau/UhhyouManuals)

Instead of migrating to new URL, I found that GitHub Pages can deploy the pages from submodule.

- [Using submodules with GitHub Pages - GitHub Docs](https://docs.github.com/en/pages/getting-started-with-github-pages/using-submodules-with-github-pages)

To update the pages, the reference to submodule must be updated. I was hoping that re-running `pages-build-deployment` action fetches the latest commit of the submodule, but that wasn't the case. `git submodule -b` is used but it's not working.

It might be better to migrate URL as initially planned.

**Comment by fotisandstuff** [comment]
Wow, this is awesome!!! Thank you for making this.
