### ISSUE TITLE
Randomize not working Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by maxxatgit** [ryukau/VSTPlugins#43]
These plugins are great, thank you!
I want to use randomize to generate new patches, but randomize  does not work on my computer.

Keyboard shortcuts do not work. Ctl + click works to reset a parameter to it's default, but all standalone keyboard shortcuts do not work.

Thank you.

**Comment by ryukau** [comment]
Hi.

A randomization and other keyboard shortcuts only works for a box of blue bars (barbox) like the one in the image below.

![スクリーンショット 2023-10-22 163522](https://github.com/ryukau/VSTPlugins/assets/6243462/7150c751-a313-4e5c-96ad-d527e53da54b)

To use it:

1. Click or move mouse wheel on a barbox to focus.
2. Stay the mouse cursor on the barbox.
3. Press <kbd>R</kbd> key.

(Probably) another person was requested the same feature for GenericDrum, so at least that synth got a bit better randomization now. I pushed the change now, so it will be available in like 30 minutes if nothing goes wrong.

**Comment by ryukau** [comment]
I just realized that you are on Ubuntu. In that case, the plugin may not receive the keyboard shortcuts. VSTGUI is a bit flaky on Linux.

I'm considering to change GUI library to something like static Qt, but it's not priority and will take long time.

**Comment by maxxatgit** [comment]
OK. Thank you for considering this.

What I was hoping for is a random function like the button on your web synthesizers at github.io. They are great for generating samples, but I would like to generate presets so that I can modulate the parameters in real time.

The plugins are still great exactly how they are now. Thank you!

**Comment by ryukau** [comment]
Which synths are you using the most? I can add randomization button but only to a few of them. This is to reduce the work when I eventually port them to other GUI library.

**Comment by maxxatgit** [comment]
Wow! That is amazing...
Generic Drum, Clang Cymbal, and FM Glassy Pad.
Thank you so much...

**Comment by ryukau** [comment]
Randomization button is added to ClangCymbal on `develop` branch. Could you test it?

GenericDrum already got a randomization button in version 0.1.1. Check out the [release page](https://github.com/ryukau/VSTPlugins/releases/tag/UhhyouPlugins0.58.0).

FMGlassyPad isn't available as a plugin. Maybe I'll work on it when I find a fast sin/cos implementation.

**Comment by maxxatgit** [comment]
I don't know how to compile/build...

I just tested the new Generic Drum - Random button is great!
There are so many parameters, it's a long process to get to a working  preset. It's great that you include presets with it.

Don't worry about FMGlassyPad, I'll just generate samples from it. It really sounds good! I have gotten some really nice Roland D-50 type sounds out of it.

Many thanks! :)

**Comment by ryukau** [comment]
Here's ClangCymbal built on Ubuntu on GitHub Actions. Is this sufficient or you'd like to have more narrow randomization?

[vst_ubuntu.zip](https://github.com/ryukau/VSTPlugins/files/13176098/vst_ubuntu.zip)

**Comment by maxxatgit** [comment]
More narrow randomization would be great. many of the randomizations do not produce any sound. The randomization on the web synth ClangCymbal works quite well. Many useful patches.

**Comment by ryukau** [comment]
Thanks for feedback. 👍 I made some changes.

[vst_ubuntu.zip](https://github.com/ryukau/VSTPlugins/files/13184423/vst_ubuntu.zip)

A difference between the web synth and the plugins is gain normalization. Web synth works offline (non real-time), so it can fix the amplitude after rendering. The plugin version can't do this because it's hard to know the max amplitude beforehand.

**Comment by maxxatgit** [comment]
Thank you!
