### ISSUE TITLE
update cairocontext patch

### ISSUE THREAD

**Issue by KottV** [ryukau/VSTPlugins#48]
Hi!

Since [vstgui4_13_0](https://github.com/steinbergmedia/vstgui/releases/tag/vstgui4_13_0) has new cairocontext implementation, so previous replacement doesn't work anymore.
Here is a patch for current version:
[cairographicscontext.patch.gz](https://github.com/ryukau/VSTPlugins/files/13757512/cairographicscontext.patch.gz)

Or I can make a pull request with these changes.

**Comment by ryukau** [comment]
Hi.

Many thanks for the patch. However, my computer is broken and I'm currently waiting for repair. It may take several weeks. I'll merge the patch when the repair is done.

**Comment by ryukau** [comment]
The patch is merged and released on UhhyouPlugins0.61.0. Thanks again for the patch.

If something is not working, feel free to add comment to this issue.

**Comment by KottV** [comment]
Thanks for merging!
Also it can be applied in `ci_ubuntu.sh` just by
`git apply --directory=lib/vst3sdk/vstgui4/ ci/linux_patch/cairographicscontext.patch` without jump in/out the vstgui4 directory.

**Comment by ryukau** [comment]
Thanks for the information. I changed the command in 89382f9.

Off topic: I actually looked up how to apply the patch to submodule, but couldn't find the answer. I should stop relying on web searches (or StackOverflow answers) and should start reading the manual more thoroughly.
