### ISSUE TITLE
PlugProcessor::setupProcessing() returns kNotImplemented

### ISSUE THREAD

**Issue by alex-tee** [ryukau/VSTPlugins#49]
It should return kResultOk. See the discussion in https://github.com/falkTX/Carla/issues/1848#issuecomment-1893471582

**Comment by ryukau** [comment]
I read the discussion on the link, and it refers to `AudioEffect::setProcessing` instead of [`AudioEffect::setupProcessing`](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/source/vst/vstaudioeffect.cpp#L169). So it's not returning `kNotImplemented`.

It's quite possible that my plugins have other kind of bugs in somewhere else.

**Comment by alex-tee** [comment]
> I read the discussion on the link, and it refers to `AudioEffect::setProcessing` instead of [`AudioEffect::setupProcessing`](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/source/vst/vstaudioeffect.cpp#L169). So it's not returning `kNotImplemented`.

Oh you're right. That's strange though, because accepting `kNotImplemented` solved the issue: https://github.com/falkTX/Carla/pull/1849

**Comment by ryukau** [comment]
Okay, I now see what's going wrong.

My plugins don't implement `setProcessing`, and it returns `kNotImplemented`. However, Carla expects `setProcessing` to be implemented.

When I started, I copied the structure of AGain which is an example plugin in VST 3 SDK. And AGain doesn't implement `setProcessing` either ([link](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/samples/vst/again/source/again.h)). The documentation about [`setProcessing`](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IAudioProcessor.html#af252fd721b195b793f3a5dfffc069401) says it is there to reset delays and reverbs for example. However, Steinberg's ADelay example plugin resets buffer in `setActive` ([link](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/samples/vst/adelay/source/adelayprocessor.cpp#L77-L112)). So, I'm not sure about the use case of `setProcessing`.

For testing plugin host, I'd recommend to use the example plugins in VST 3 SDK, especially AGain and NoteExpressionSynth. I guess many people including me wrote their plugins based on these examples.

It seems that your patch to Carla fixes the issue, so I close this issue. If there's still something, please feel free to add comment, or open another issue.

Reference:

- [Audio Processor Call Sequence - VST 3 Developer Portal](https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Workflow+Diagrams/Audio+Processor+Call+Sequence.html)
- [VST 3 Interfaces: IAudioProcessor Class Reference](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IAudioProcessor.html#af252fd721b195b793f3a5dfffc069401)
- [vst3_pluginterfaces/vst/ivstaudioprocessor.h at f0eeef7ca771f3cac2dfe1922dc5733349766c7b · steinbergmedia/vst3_pluginterfaces · GitHub](https://github.com/steinbergmedia/vst3_pluginterfaces/blob/f0eeef7ca771f3cac2dfe1922dc5733349766c7b/vst/ivstaudioprocessor.h#L305-L314)
- [vst3_public_sdk/samples/vst/again/source/again.h at e61ee76eb0f8771a05e99018bc4705ac1b603e48 · steinbergmedia/vst3_public_sdk · GitHub](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/samples/vst/again/source/again.h)
- [vst3_public_sdk/samples/vst/adelay/source/adelayprocessor.cpp at e61ee76eb0f8771a05e99018bc4705ac1b603e48 · steinbergmedia/vst3_public_sdk · GitHub](https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/samples/vst/adelay/source/adelayprocessor.cpp#L77-L112)

**Comment by alex-tee** [comment]
>For testing plugin host, I'd recommend to use the example plugins in VST 3 SDK, especially AGain and NoteExpressionSynth. I guess many people including me wrote their plugins based on these examples.

Fair, thanks
