### ISSUE TITLE
GenericDrum is recognized as a vst effects plugin in Studio One

### ISSUE THREAD

**Issue by jzt15j** [ryukau/VSTPlugins#51]

**Comment by ryukau** [comment]
GenericDrum is both an effect and a synth. If the plugin doesn't show up as both, then it's an issue of host application. I'd recommend to contact a support of Studio One.

The plugin category is set to `kFxInstrument` in `GenericDrum/source/plugfactory.cpp`. If you can build from source code, fastest work around is to change the category to `kInstrumentSynth`.
