### ISSUE TITLE
Suggestion for GlitchSprinkler

### ISSUE THREAD

**Issue by arseniiv** [ryukau/VSTPlugins#52]
Hi! Do you want to try adding an additional playback mode for the synth where the pitches are more true without compromising integer sample count of individual periods. (I’m not sure if it would always sound good but it should be not too complicated to try out and decide.) The idea is using periods of N samples and periods of N−1 samples at different times, making the average frequency more precise than a period of N or N−1 samples can get by themselves.

The basic idea of which period to choose is as in [Bresenham’s line drawing algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm). I already proposed to do the same for another plugin which is also sample-perfect by design: [(comment)](https://github.com/robbert-vdh/nih-plug/issues/138#issuecomment-2043386056). Translating my pseudocode from there, we have:

```c
// init either at the very start or after each note on:
phase = 0;  // can be arbitrary in range [0; 1)

// init after each note on, note frequency being `f`:
period = sampleRate / f;
smallerPeriod = floor(period);
delta = period - smallerPeriod;

// while filling in an outgoing buffer when a note is on:
while (...) {
    phase += delta;
    longerPeriodNext = (phase >= 1);
    if (longerPeriodNext) {
        phase -= 1;
    }
    addMoreSamples(longerPeriodNext);
}
```

I renamed a couple variables to make it clearer and applicable to this here case.

Though now I see this code might be a bit incorrect when you have the desirable period be exactly an integer amount of samples (and `delta` exactly zero). That’s because `phase` can be less than zero but I implied it won’t. Hmmm. I’ll edit the code a little bit later. When `delta` is not exactly zero, the code should work flawlessly because `phase` will be all over the place—it’s just this corner case that’s wrong.

EDIT: I think I already fixed it!

[Initially I wrote this in a Youtube comment but it got deleted again. I don’t know why I bothered when here I can link related stuff and make the code formatted...]

**Comment by ryukau** [comment]
I implemented your method in Python 3. Could you review that the code matches your description?

https://gist.github.com/ryukau/6c6395780bd0f58be19b7268e7f40b75

I'll make some points after confirming that the code is correct.

**Comment by arseniiv** [comment]
I think it’s correct! 🤝 Haven’t run the code for myself but if you see reasonable frequency glides on the spectrogram when trying to change `frequencyHz` smoothly, then that’s more evidence it’s working as intended. (Though I’d test it on a sine waveform, not just on sawtooth, for the spectrum to be clearer.)

**Comment by arseniiv** [comment]
Yeah I see, indeed too much of other frequencies get added and are very prominent. That’s unfortunate. Thanks for testing it out!
