### ISSUE TITLE
Active tab label is uncolored.

### ISSUE THREAD

**Issue by KottV** [ryukau/VSTPlugins#6]
Greetings,

Thank for porting palette to VST version. I found that text on active tab is colored with **foregroundInactive**.

I fixed that by just adding in tabview.cpp:

```
 // Active tab.
+  pContext->setFontColor(pal.foreground());
```

And I'd like to add another one addition to palette for text label's strokes. Could you accept that?

**Comment by ryukau** [comment]
Thanks for the catch. Active tab color is fixed in latest commit.

I can't promise without looking concrete example (code or screenshot/screencast of improvement). But if it's only some addition to the palette, I'll probably merge that.

**Comment by KottV** [comment]
The idea is to add color config for lines near the text label. Currently it inherits color from border. So it will be possible to draw them with borderless theme:

![Screenshot_20200616_122921](https://user-images.githubusercontent.com/4686351/84725284-9a4b3d00-afcd-11ea-83b1-a1ffd6bbe8c6.png)

Will be:

![Screenshot_20200616_122746](https://user-images.githubusercontent.com/4686351/84725307-aa631c80-afcd-11ea-9b1b-8700bc01a15b.png)

I've made it by add **borderLabel** color to palette and:

```
+++ label.hpp   2020-06-15 14:51:33.319926072 +1000
@@ -54,7 +54,7 @@
       beginPath();
       moveTo(0, height / 2);
       lineTo(width, height / 2);
-      strokeColor(pal.border());
+      strokeColor(pal.borderLabel());
       strokeWidth(borderWidth);
       stroke();
```

**Comment by ryukau** [comment]
Thanks for the explanation.

I'll merge it. Feel free to open PR when the patch is ready.
